/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The response data
*/
export class AddRoleAssignmentResponse200AllOfData {
    /**
    * The ID of the user that was added to the role
    */
    'userId'?: number;
    /**
    * The ID of the role the user was added to
    */
    'roleId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number"
        },
        {
            "name": "roleId",
            "baseName": "role_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AddRoleAssignmentResponse200AllOfData.attributeTypeMap;
    }
}

