/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BasicOrganization {
    /**
    * The ID of the user who will be marked as the owner of this organization. When omitted, the authorized user ID will be used.
    */
    'ownerId'?: number;
    'visibleTo'?: BasicOrganization.VisibleToEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ownerId",
            "baseName": "owner_id",
            "type": "number"
        },
        {
            "name": "visibleTo",
            "baseName": "visible_to",
            "type": "BasicOrganization.VisibleToEnum"
        }    ];

    static getAttributeTypeMap() {
        return BasicOrganization.attributeTypeMap;
    }
}

export namespace BasicOrganization {
    export enum VisibleToEnum {
        _1 = <any> '1',
        _3 = <any> '3',
        _5 = <any> '5',
        _7 = <any> '7'
    }
}
