/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityResponseObject } from './activityResponseObject';
import { GetActivitiesResponse200AdditionalData } from './getActivitiesResponse200AdditionalData';
import { GetActivitiesResponse200RelatedObjects } from './getActivitiesResponse200RelatedObjects';

export class GetActivitiesResponse200 {
    'success'?: boolean;
    'data'?: Array<ActivityResponseObject>;
    'additionalData'?: GetActivitiesResponse200AdditionalData;
    'relatedObjects'?: GetActivitiesResponse200RelatedObjects;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<ActivityResponseObject>"
        },
        {
            "name": "additionalData",
            "baseName": "additional_data",
            "type": "GetActivitiesResponse200AdditionalData"
        },
        {
            "name": "relatedObjects",
            "baseName": "related_objects",
            "type": "GetActivitiesResponse200RelatedObjects"
        }    ];

    static getAttributeTypeMap() {
        return GetActivitiesResponse200.attributeTypeMap;
    }
}

