/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetCommentsResponse200DataInner {
    /**
    * The ID of the note
    */
    'uuid'?: string;
    /**
    * Whether the note is active or deleted
    */
    'activeFlag'?: boolean;
    /**
    * The creation date and time of the note
    */
    'addTime'?: string;
    /**
    * The creation date and time of the note
    */
    'updateTime'?: string;
    /**
    * The content of the note in HTML format. Subject to sanitization on the back-end.
    */
    'content'?: string;
    /**
    * The ID of the object that the comment is attached to, will be the id of the note
    */
    'objectId'?: string;
    /**
    * The type of object that the comment is attached to, will be \"note\"
    */
    'objectType'?: string;
    /**
    * The ID of the user who created the comment
    */
    'userId'?: number;
    /**
    * The ID of the user who last updated the comment
    */
    'updaterId'?: number;
    /**
    * The ID of the company
    */
    'companyId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "activeFlag",
            "baseName": "active_flag",
            "type": "boolean"
        },
        {
            "name": "addTime",
            "baseName": "add_time",
            "type": "string"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "objectId",
            "baseName": "object_id",
            "type": "string"
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number"
        },
        {
            "name": "updaterId",
            "baseName": "updater_id",
            "type": "number"
        },
        {
            "name": "companyId",
            "baseName": "company_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetCommentsResponse200DataInner.attributeTypeMap;
    }
}

