/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddActivityResponse200RelatedObjectsOrganization } from './addActivityResponse200RelatedObjectsOrganization';
import { AddActivityResponse200RelatedObjectsPerson } from './addActivityResponse200RelatedObjectsPerson';
import { GetActivitiesResponse200RelatedObjectsDeal } from './getActivitiesResponse200RelatedObjectsDeal';
import { GetActivitiesResponse200RelatedObjectsUser } from './getActivitiesResponse200RelatedObjectsUser';

export class GetDealActivitiesResponse200AllOfRelatedObjects {
    'organization'?: AddActivityResponse200RelatedObjectsOrganization;
    'person'?: AddActivityResponse200RelatedObjectsPerson;
    'deal'?: GetActivitiesResponse200RelatedObjectsDeal;
    'user'?: GetActivitiesResponse200RelatedObjectsUser;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "organization",
            "baseName": "organization",
            "type": "AddActivityResponse200RelatedObjectsOrganization"
        },
        {
            "name": "person",
            "baseName": "person",
            "type": "AddActivityResponse200RelatedObjectsPerson"
        },
        {
            "name": "deal",
            "baseName": "deal",
            "type": "GetActivitiesResponse200RelatedObjectsDeal"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "GetActivitiesResponse200RelatedObjectsUser"
        }    ];

    static getAttributeTypeMap() {
        return GetDealActivitiesResponse200AllOfRelatedObjects.attributeTypeMap;
    }
}

