/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetNotesResponse200DataInnerDeal } from './getNotesResponse200DataInnerDeal';
import { GetNotesResponse200DataInnerOrganization } from './getNotesResponse200DataInnerOrganization';
import { GetNotesResponse200DataInnerPerson } from './getNotesResponse200DataInnerPerson';
import { GetNotesResponse200DataInnerUser } from './getNotesResponse200DataInnerUser';

export class GetNotesResponse200DataInner {
    /**
    * The ID of the note
    */
    'id'?: number;
    /**
    * Whether the note is active or deleted
    */
    'activeFlag'?: boolean;
    /**
    * The creation date and time of the note
    */
    'addTime'?: string;
    /**
    * The content of the note in HTML format. Subject to sanitization on the back-end.
    */
    'content'?: string;
    'deal'?: GetNotesResponse200DataInnerDeal;
    /**
    * The ID of the lead the note is attached to
    */
    'leadId'?: string;
    /**
    * The ID of the deal the note is attached to
    */
    'dealId'?: number;
    /**
    * The ID of the user who last updated the note
    */
    'lastUpdateUserId'?: number;
    /**
    * The ID of the organization the note is attached to
    */
    'orgId'?: number;
    'organization'?: GetNotesResponse200DataInnerOrganization;
    'person'?: GetNotesResponse200DataInnerPerson;
    /**
    * The ID of the person the note is attached to
    */
    'personId'?: number;
    /**
    * If true, the results are filtered by note to deal pinning state
    */
    'pinnedToDealFlag'?: boolean;
    /**
    * If true, the results are filtered by note to organization pinning state
    */
    'pinnedToOrganizationFlag'?: boolean;
    /**
    * If true, the results are filtered by note to person pinning state
    */
    'pinnedToPersonFlag'?: boolean;
    /**
    * The last updated date and time of the note
    */
    'updateTime'?: string;
    'user'?: GetNotesResponse200DataInnerUser;
    /**
    * The ID of the note creator
    */
    'userId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "activeFlag",
            "baseName": "active_flag",
            "type": "boolean"
        },
        {
            "name": "addTime",
            "baseName": "add_time",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "deal",
            "baseName": "deal",
            "type": "GetNotesResponse200DataInnerDeal"
        },
        {
            "name": "leadId",
            "baseName": "lead_id",
            "type": "string"
        },
        {
            "name": "dealId",
            "baseName": "deal_id",
            "type": "number"
        },
        {
            "name": "lastUpdateUserId",
            "baseName": "last_update_user_id",
            "type": "number"
        },
        {
            "name": "orgId",
            "baseName": "org_id",
            "type": "number"
        },
        {
            "name": "organization",
            "baseName": "organization",
            "type": "GetNotesResponse200DataInnerOrganization"
        },
        {
            "name": "person",
            "baseName": "person",
            "type": "GetNotesResponse200DataInnerPerson"
        },
        {
            "name": "personId",
            "baseName": "person_id",
            "type": "number"
        },
        {
            "name": "pinnedToDealFlag",
            "baseName": "pinned_to_deal_flag",
            "type": "boolean"
        },
        {
            "name": "pinnedToOrganizationFlag",
            "baseName": "pinned_to_organization_flag",
            "type": "boolean"
        },
        {
            "name": "pinnedToPersonFlag",
            "baseName": "pinned_to_person_flag",
            "type": "boolean"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "GetNotesResponse200DataInnerUser"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetNotesResponse200DataInner.attributeTypeMap;
    }
}

