/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetAssociatedFilesResponse200AllOfDataInner } from './getAssociatedFilesResponse200AllOfDataInner';

export class GetRecentsResponse200DataInnerAnyOf3 {
    'item'?: GetRecentsResponse200DataInnerAnyOf3.ItemEnum;
    'id'?: number;
    'data'?: GetAssociatedFilesResponse200AllOfDataInner;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "item",
            "baseName": "item",
            "type": "GetRecentsResponse200DataInnerAnyOf3.ItemEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "GetAssociatedFilesResponse200AllOfDataInner"
        }    ];

    static getAttributeTypeMap() {
        return GetRecentsResponse200DataInnerAnyOf3.attributeTypeMap;
    }
}

export namespace GetRecentsResponse200DataInnerAnyOf3 {
    export enum ItemEnum {
        File = <any> 'file'
    }
}
