/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DealStrict } from './dealStrict';

export class GetRecentsResponse200DataInnerAnyOf2 {
    'item'?: GetRecentsResponse200DataInnerAnyOf2.ItemEnum;
    'id'?: number;
    'data'?: DealStrict;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "item",
            "baseName": "item",
            "type": "GetRecentsResponse200DataInnerAnyOf2.ItemEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "DealStrict"
        }    ];

    static getAttributeTypeMap() {
        return GetRecentsResponse200DataInnerAnyOf2.attributeTypeMap;
    }
}

export namespace GetRecentsResponse200DataInnerAnyOf2 {
    export enum ItemEnum {
        Deal = <any> 'deal'
    }
}
