/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetUserSettingsResponse200AllOfData {
    /**
    * If the vendors are allowed to install custom Marketplace apps with functionality and content in the Pipedrive UI or not
    */
    'marketplaceAllowCustomInstallUrl'?: boolean;
    /**
    * If the vendors are allowed to extend their Marketplace apps with functionality and content in the Pipedrive UI or not
    */
    'marketplaceAppExtensionsVendor'?: boolean;
    /**
    * If the vendors are allowed to be part of the Marketplace team or not
    */
    'marketplaceTeam'?: boolean;
    /**
    * The number of results shown in list by default
    */
    'listLimit'?: number;
    /**
    * Whether beta app is enabled
    */
    'betaApp'?: boolean;
    /**
    * Prevent salesphone call to override
    */
    'preventSalesphoneCalltoOverride'?: boolean;
    /**
    * The destination of file upload
    */
    'fileUploadDestination'?: string;
    /**
    * The call to link syntax
    */
    'calltoLinkSyntax'?: string;
    /**
    * Whether the expected close date of the deal is filled automatically or not
    */
    'autofillDealExpectedCloseDate'?: boolean;
    /**
    * Allow the vendors to duplicate a person
    */
    'personDuplicateCondition'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "marketplaceAllowCustomInstallUrl",
            "baseName": "marketplace_allow_custom_install_url",
            "type": "boolean"
        },
        {
            "name": "marketplaceAppExtensionsVendor",
            "baseName": "marketplace_app_extensions_vendor",
            "type": "boolean"
        },
        {
            "name": "marketplaceTeam",
            "baseName": "marketplace_team",
            "type": "boolean"
        },
        {
            "name": "listLimit",
            "baseName": "list_limit",
            "type": "number"
        },
        {
            "name": "betaApp",
            "baseName": "beta_app",
            "type": "boolean"
        },
        {
            "name": "preventSalesphoneCalltoOverride",
            "baseName": "prevent_salesphone_callto_override",
            "type": "boolean"
        },
        {
            "name": "fileUploadDestination",
            "baseName": "file_upload_destination",
            "type": "string"
        },
        {
            "name": "calltoLinkSyntax",
            "baseName": "callto_link_syntax",
            "type": "string"
        },
        {
            "name": "autofillDealExpectedCloseDate",
            "baseName": "autofill_deal_expected_close_date",
            "type": "boolean"
        },
        {
            "name": "personDuplicateCondition",
            "baseName": "person_duplicate_condition",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetUserSettingsResponse200AllOfData.attributeTypeMap;
    }
}

