/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OrganizationItemAllOf {
    /**
    * Please refer to response schema of <a href=\"https://developers.pipedrive.com/docs/api/v1/Activities#getActivity\">Activity</a>
    */
    'lastActivity'?: object;
    /**
    * Please refer to response schema of <a href=\"https://developers.pipedrive.com/docs/api/v1/Activities#getActivity\">Activity</a>
    */
    'nextActivity'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lastActivity",
            "baseName": "last_activity",
            "type": "object"
        },
        {
            "name": "nextActivity",
            "baseName": "next_activity",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return OrganizationItemAllOf.attributeTypeMap;
    }
}

