/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RelationshipOrganizationInfoItem } from './relationshipOrganizationInfoItem';

export class OrganizationRelationshipWithCalculatedFieldsAllOf {
    /**
    * The ID of the organization relationship
    */
    'id'?: number;
    /**
    * The type of the relationship
    */
    'type'?: string;
    'relOwnerOrgId'?: RelationshipOrganizationInfoItem;
    'relLinkedOrgId'?: RelationshipOrganizationInfoItem;
    /**
    * The creation date and time of the relationship
    */
    'addTime'?: string;
    /**
    * The last updated date and time of the relationship
    */
    'updateTime'?: string;
    /**
    * Whether the relationship is active or not
    */
    'activeFlag'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "relOwnerOrgId",
            "baseName": "rel_owner_org_id",
            "type": "RelationshipOrganizationInfoItem"
        },
        {
            "name": "relLinkedOrgId",
            "baseName": "rel_linked_org_id",
            "type": "RelationshipOrganizationInfoItem"
        },
        {
            "name": "addTime",
            "baseName": "add_time",
            "type": "string"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "string"
        },
        {
            "name": "activeFlag",
            "baseName": "active_flag",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrganizationRelationshipWithCalculatedFieldsAllOf.attributeTypeMap;
    }
}

