/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SearchItemResponse200AllOfDataItemsInner } from './searchItemResponse200AllOfDataItemsInner';

export class SearchItemResponse200AllOfData {
    /**
    * The array of found items
    */
    'items'?: Array<SearchItemResponse200AllOfDataItemsInner>;
    /**
    * The array of related items if `search_for_related_items` was enabled
    */
    'relatedItems'?: Array<SearchItemResponse200AllOfDataItemsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<SearchItemResponse200AllOfDataItemsInner>"
        },
        {
            "name": "relatedItems",
            "baseName": "related_items",
            "type": "Array<SearchItemResponse200AllOfDataItemsInner>"
        }    ];

    static getAttributeTypeMap() {
        return SearchItemResponse200AllOfData.attributeTypeMap;
    }
}

