/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddCallLogResponse200AllOfData } from './AddCallLogResponse200AllOfData';
import {
    AddCallLogResponse200AllOfDataFromJSON,
    AddCallLogResponse200AllOfDataFromJSONTyped,
    AddCallLogResponse200AllOfDataToJSON,
} from './AddCallLogResponse200AllOfData';

/**
 * 
 * @export
 * @interface AddCallLogResponse200AllOf
 */
export interface AddCallLogResponse200AllOf {
    /**
     * 
     * @type {AddCallLogResponse200AllOfData}
     * @memberof AddCallLogResponse200AllOf
     */
    data?: AddCallLogResponse200AllOfData;
}

/**
 * Check if a given object implements the AddCallLogResponse200AllOf interface.
 */
export function instanceOfAddCallLogResponse200AllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddCallLogResponse200AllOfFromJSON(json: any): AddCallLogResponse200AllOf {
    return AddCallLogResponse200AllOfFromJSONTyped(json, false);
}

export function AddCallLogResponse200AllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCallLogResponse200AllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : AddCallLogResponse200AllOfDataFromJSON(json['data']),
    };
}

export function AddCallLogResponse200AllOfToJSON(value?: AddCallLogResponse200AllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AddCallLogResponse200AllOfDataToJSON(value.data),
    };
}

