/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddDealFollowerRequest
 */
export interface AddDealFollowerRequest {
    /**
     * The ID of the user
     * @type {number}
     * @memberof AddDealFollowerRequest
     */
    user_id: number;
}

/**
 * Check if a given object implements the AddDealFollowerRequest interface.
 */
export function instanceOfAddDealFollowerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user_id" in value;

    return isInstance;
}

export function AddDealFollowerRequestFromJSON(json: any): AddDealFollowerRequest {
    return AddDealFollowerRequestFromJSONTyped(json, false);
}

export function AddDealFollowerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddDealFollowerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
    };
}

export function AddDealFollowerRequestToJSON(value?: AddDealFollowerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.user_id,
    };
}

