/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddDealRequestAllOf
 */
export interface AddDealRequestAllOf {
    /**
     * The optional creation date & time of the deal in UTC. Requires admin user API token. Format: YYYY-MM-DD HH:MM:SS
     * @type {string}
     * @memberof AddDealRequestAllOf
     */
    add_time?: string;
}

/**
 * Check if a given object implements the AddDealRequestAllOf interface.
 */
export function instanceOfAddDealRequestAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddDealRequestAllOfFromJSON(json: any): AddDealRequestAllOf {
    return AddDealRequestAllOfFromJSONTyped(json, false);
}

export function AddDealRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddDealRequestAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'add_time': !exists(json, 'add_time') ? undefined : json['add_time'],
    };
}

export function AddDealRequestAllOfToJSON(value?: AddDealRequestAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'add_time': value.add_time,
    };
}

