/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddDealParticipantResponse200Data } from './AddDealParticipantResponse200Data';
import {
    AddDealParticipantResponse200DataFromJSON,
    AddDealParticipantResponse200DataFromJSONTyped,
    AddDealParticipantResponse200DataToJSON,
} from './AddDealParticipantResponse200Data';
import type { GetDealsResponse200RelatedObjects } from './GetDealsResponse200RelatedObjects';
import {
    GetDealsResponse200RelatedObjectsFromJSON,
    GetDealsResponse200RelatedObjectsFromJSONTyped,
    GetDealsResponse200RelatedObjectsToJSON,
} from './GetDealsResponse200RelatedObjects';

/**
 * 
 * @export
 * @interface AddDealParticipantResponse200
 */
export interface AddDealParticipantResponse200 {
    /**
     * If the request was successful or not
     * @type {boolean}
     * @memberof AddDealParticipantResponse200
     */
    success?: boolean;
    /**
     * 
     * @type {AddDealParticipantResponse200Data}
     * @memberof AddDealParticipantResponse200
     */
    data?: AddDealParticipantResponse200Data;
    /**
     * 
     * @type {GetDealsResponse200RelatedObjects}
     * @memberof AddDealParticipantResponse200
     */
    related_objects?: GetDealsResponse200RelatedObjects;
}

/**
 * Check if a given object implements the AddDealParticipantResponse200 interface.
 */
export function instanceOfAddDealParticipantResponse200(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddDealParticipantResponse200FromJSON(json: any): AddDealParticipantResponse200 {
    return AddDealParticipantResponse200FromJSONTyped(json, false);
}

export function AddDealParticipantResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): AddDealParticipantResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : AddDealParticipantResponse200DataFromJSON(json['data']),
        'related_objects': !exists(json, 'related_objects') ? undefined : GetDealsResponse200RelatedObjectsFromJSON(json['related_objects']),
    };
}

export function AddDealParticipantResponse200ToJSON(value?: AddDealParticipantResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'data': AddDealParticipantResponse200DataToJSON(value.data),
        'related_objects': GetDealsResponse200RelatedObjectsToJSON(value.related_objects),
    };
}

