/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseOrganizationItemWithEditNameFlag } from './BaseOrganizationItemWithEditNameFlag';
import {
    BaseOrganizationItemWithEditNameFlagFromJSON,
    BaseOrganizationItemWithEditNameFlagFromJSONTyped,
    BaseOrganizationItemWithEditNameFlagToJSON,
} from './BaseOrganizationItemWithEditNameFlag';
import type { GetOrganizationsResponse200AllOfRelatedObjects } from './GetOrganizationsResponse200AllOfRelatedObjects';
import {
    GetOrganizationsResponse200AllOfRelatedObjectsFromJSON,
    GetOrganizationsResponse200AllOfRelatedObjectsFromJSONTyped,
    GetOrganizationsResponse200AllOfRelatedObjectsToJSON,
} from './GetOrganizationsResponse200AllOfRelatedObjects';

/**
 * 
 * @export
 * @interface AddOrganizationResponse200AllOf
 */
export interface AddOrganizationResponse200AllOf {
    /**
     * 
     * @type {BaseOrganizationItemWithEditNameFlag}
     * @memberof AddOrganizationResponse200AllOf
     */
    data?: BaseOrganizationItemWithEditNameFlag;
    /**
     * 
     * @type {GetOrganizationsResponse200AllOfRelatedObjects}
     * @memberof AddOrganizationResponse200AllOf
     */
    related_objects?: GetOrganizationsResponse200AllOfRelatedObjects;
}

/**
 * Check if a given object implements the AddOrganizationResponse200AllOf interface.
 */
export function instanceOfAddOrganizationResponse200AllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddOrganizationResponse200AllOfFromJSON(json: any): AddOrganizationResponse200AllOf {
    return AddOrganizationResponse200AllOfFromJSONTyped(json, false);
}

export function AddOrganizationResponse200AllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOrganizationResponse200AllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : BaseOrganizationItemWithEditNameFlagFromJSON(json['data']),
        'related_objects': !exists(json, 'related_objects') ? undefined : GetOrganizationsResponse200AllOfRelatedObjectsFromJSON(json['related_objects']),
    };
}

export function AddOrganizationResponse200AllOfToJSON(value?: AddOrganizationResponse200AllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': BaseOrganizationItemWithEditNameFlagToJSON(value.data),
        'related_objects': GetOrganizationsResponse200AllOfRelatedObjectsToJSON(value.related_objects),
    };
}

