/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddPipelineResponse200AllOfData } from './AddPipelineResponse200AllOfData';
import {
    AddPipelineResponse200AllOfDataFromJSON,
    AddPipelineResponse200AllOfDataFromJSONTyped,
    AddPipelineResponse200AllOfDataToJSON,
} from './AddPipelineResponse200AllOfData';

/**
 * 
 * @export
 * @interface AddPipelineResponse200
 */
export interface AddPipelineResponse200 {
    /**
     * If the response is successful or not
     * @type {boolean}
     * @memberof AddPipelineResponse200
     */
    success?: boolean;
    /**
     * 
     * @type {AddPipelineResponse200AllOfData}
     * @memberof AddPipelineResponse200
     */
    data?: AddPipelineResponse200AllOfData;
}

/**
 * Check if a given object implements the AddPipelineResponse200 interface.
 */
export function instanceOfAddPipelineResponse200(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddPipelineResponse200FromJSON(json: any): AddPipelineResponse200 {
    return AddPipelineResponse200FromJSONTyped(json, false);
}

export function AddPipelineResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPipelineResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : AddPipelineResponse200AllOfDataFromJSON(json['data']),
    };
}

export function AddPipelineResponse200ToJSON(value?: AddPipelineResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'data': AddPipelineResponse200AllOfDataToJSON(value.data),
    };
}

