/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The pipeline object
 * @export
 * @interface AddPipelineResponse200AllOfData
 */
export interface AddPipelineResponse200AllOfData {
    /**
     * The ID of the pipeline
     * @type {number}
     * @memberof AddPipelineResponse200AllOfData
     */
    id?: number;
    /**
     * The name of the pipeline
     * @type {string}
     * @memberof AddPipelineResponse200AllOfData
     */
    name?: string;
    /**
     * The pipeline title displayed in the URL
     * @type {string}
     * @memberof AddPipelineResponse200AllOfData
     */
    url_title?: string;
    /**
     * Defines the order of pipelines. First order (`order_nr=0`) is the default pipeline.
     * @type {number}
     * @memberof AddPipelineResponse200AllOfData
     */
    order_nr?: number;
    /**
     * Whether this pipeline will be made inactive (hidden) or active
     * @type {boolean}
     * @memberof AddPipelineResponse200AllOfData
     */
    active?: boolean;
    /**
     * Whether deal probability is disabled or enabled for this pipeline
     * @type {boolean}
     * @memberof AddPipelineResponse200AllOfData
     */
    deal_probability?: boolean;
    /**
     * The pipeline creation time. Format: YYYY-MM-DD HH:MM:SS.
     * @type {string}
     * @memberof AddPipelineResponse200AllOfData
     */
    add_time?: string;
    /**
     * The pipeline update time. Format: YYYY-MM-DD HH:MM:SS.
     * @type {string}
     * @memberof AddPipelineResponse200AllOfData
     */
    update_time?: string;
}

/**
 * Check if a given object implements the AddPipelineResponse200AllOfData interface.
 */
export function instanceOfAddPipelineResponse200AllOfData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddPipelineResponse200AllOfDataFromJSON(json: any): AddPipelineResponse200AllOfData {
    return AddPipelineResponse200AllOfDataFromJSONTyped(json, false);
}

export function AddPipelineResponse200AllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPipelineResponse200AllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'url_title': !exists(json, 'url_title') ? undefined : json['url_title'],
        'order_nr': !exists(json, 'order_nr') ? undefined : json['order_nr'],
        'active': !exists(json, 'active') ? undefined : json['active'],
        'deal_probability': !exists(json, 'deal_probability') ? undefined : json['deal_probability'],
        'add_time': !exists(json, 'add_time') ? undefined : json['add_time'],
        'update_time': !exists(json, 'update_time') ? undefined : json['update_time'],
    };
}

export function AddPipelineResponse200AllOfDataToJSON(value?: AddPipelineResponse200AllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'url_title': value.url_title,
        'order_nr': value.order_nr,
        'active': value.active,
        'deal_probability': value.deal_probability,
        'add_time': value.add_time,
        'update_time': value.update_time,
    };
}

