/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DealPersonDataWithIdAllOfEmailInner
 */
export interface DealPersonDataWithIdAllOfEmailInner {
    /**
     * The type of the email
     * @type {string}
     * @memberof DealPersonDataWithIdAllOfEmailInner
     */
    label?: string;
    /**
     * The email of the associated person
     * @type {string}
     * @memberof DealPersonDataWithIdAllOfEmailInner
     */
    value?: string;
    /**
     * If this is the primary email or not
     * @type {boolean}
     * @memberof DealPersonDataWithIdAllOfEmailInner
     */
    primary?: boolean;
}

/**
 * Check if a given object implements the DealPersonDataWithIdAllOfEmailInner interface.
 */
export function instanceOfDealPersonDataWithIdAllOfEmailInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DealPersonDataWithIdAllOfEmailInnerFromJSON(json: any): DealPersonDataWithIdAllOfEmailInner {
    return DealPersonDataWithIdAllOfEmailInnerFromJSONTyped(json, false);
}

export function DealPersonDataWithIdAllOfEmailInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DealPersonDataWithIdAllOfEmailInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': !exists(json, 'label') ? undefined : json['label'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'primary': !exists(json, 'primary') ? undefined : json['primary'],
    };
}

export function DealPersonDataWithIdAllOfEmailInnerToJSON(value?: DealPersonDataWithIdAllOfEmailInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'value': value.value,
        'primary': value.primary,
    };
}

