/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteNoteResponse200
 */
export interface DeleteNoteResponse200 {
    /**
     * If the request was successful or not
     * @type {boolean}
     * @memberof DeleteNoteResponse200
     */
    success?: boolean;
    /**
     * If the response is successful or not
     * @type {boolean}
     * @memberof DeleteNoteResponse200
     */
    data?: boolean;
}

/**
 * Check if a given object implements the DeleteNoteResponse200 interface.
 */
export function instanceOfDeleteNoteResponse200(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteNoteResponse200FromJSON(json: any): DeleteNoteResponse200 {
    return DeleteNoteResponse200FromJSONTyped(json, false);
}

export function DeleteNoteResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteNoteResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function DeleteNoteResponse200ToJSON(value?: DeleteNoteResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'data': value.data,
    };
}

