/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeleteStagesResponse200Data } from './DeleteStagesResponse200Data';
import {
    DeleteStagesResponse200DataFromJSON,
    DeleteStagesResponse200DataFromJSONTyped,
    DeleteStagesResponse200DataToJSON,
} from './DeleteStagesResponse200Data';

/**
 * 
 * @export
 * @interface DeleteStagesResponse200
 */
export interface DeleteStagesResponse200 {
    /**
     * If the request was successful or not
     * @type {boolean}
     * @memberof DeleteStagesResponse200
     */
    success?: boolean;
    /**
     * 
     * @type {DeleteStagesResponse200Data}
     * @memberof DeleteStagesResponse200
     */
    data?: DeleteStagesResponse200Data;
}

/**
 * Check if a given object implements the DeleteStagesResponse200 interface.
 */
export function instanceOfDeleteStagesResponse200(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteStagesResponse200FromJSON(json: any): DeleteStagesResponse200 {
    return DeleteStagesResponse200FromJSONTyped(json, false);
}

export function DeleteStagesResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteStagesResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : DeleteStagesResponse200DataFromJSON(json['data']),
    };
}

export function DeleteStagesResponse200ToJSON(value?: DeleteStagesResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'data': DeleteStagesResponse200DataToJSON(value.data),
    };
}

