/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseMailThread } from './BaseMailThread';
import {
    BaseMailThreadFromJSON,
    BaseMailThreadFromJSONTyped,
    BaseMailThreadToJSON,
} from './BaseMailThread';

/**
 * 
 * @export
 * @interface DeleteMailThreadResponse200AllOf
 */
export interface DeleteMailThreadResponse200AllOf {
    /**
     * An array of mail threads
     * @type {Array<BaseMailThread>}
     * @memberof DeleteMailThreadResponse200AllOf
     */
    data?: Array<BaseMailThread>;
}

/**
 * Check if a given object implements the DeleteMailThreadResponse200AllOf interface.
 */
export function instanceOfDeleteMailThreadResponse200AllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteMailThreadResponse200AllOfFromJSON(json: any): DeleteMailThreadResponse200AllOf {
    return DeleteMailThreadResponse200AllOfFromJSONTyped(json, false);
}

export function DeleteMailThreadResponse200AllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteMailThreadResponse200AllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(BaseMailThreadFromJSON)),
    };
}

export function DeleteMailThreadResponse200AllOfToJSON(value?: DeleteMailThreadResponse200AllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(BaseMailThreadToJSON)),
    };
}

