/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteFieldsResponse200AllOfData
 */
export interface DeleteFieldsResponse200AllOfData {
    /**
     * The list of deleted field IDs
     * @type {Array<number>}
     * @memberof DeleteFieldsResponse200AllOfData
     */
    id?: Array<number>;
}

/**
 * Check if a given object implements the DeleteFieldsResponse200AllOfData interface.
 */
export function instanceOfDeleteFieldsResponse200AllOfData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteFieldsResponse200AllOfDataFromJSON(json: any): DeleteFieldsResponse200AllOfData {
    return DeleteFieldsResponse200AllOfDataFromJSONTyped(json, false);
}

export function DeleteFieldsResponse200AllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteFieldsResponse200AllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function DeleteFieldsResponse200AllOfDataToJSON(value?: DeleteFieldsResponse200AllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

