/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FieldsResponse200AllOfDataInner } from './FieldsResponse200AllOfDataInner';
import {
    FieldsResponse200AllOfDataInnerFromJSON,
    FieldsResponse200AllOfDataInnerFromJSONTyped,
    FieldsResponse200AllOfDataInnerToJSON,
} from './FieldsResponse200AllOfDataInner';

/**
 * 
 * @export
 * @interface FieldResponse200
 */
export interface FieldResponse200 {
    /**
     * If the response is successful or not
     * @type {boolean}
     * @memberof FieldResponse200
     */
    success?: boolean;
    /**
     * 
     * @type {FieldsResponse200AllOfDataInner}
     * @memberof FieldResponse200
     */
    data?: FieldsResponse200AllOfDataInner;
}

/**
 * Check if a given object implements the FieldResponse200 interface.
 */
export function instanceOfFieldResponse200(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FieldResponse200FromJSON(json: any): FieldResponse200 {
    return FieldResponse200FromJSONTyped(json, false);
}

export function FieldResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : FieldsResponse200AllOfDataInnerFromJSON(json['data']),
    };
}

export function FieldResponse200ToJSON(value?: FieldResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'data': FieldsResponse200AllOfDataInnerToJSON(value.data),
    };
}

