/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddActivityResponse200RelatedObjectsOrganization } from './AddActivityResponse200RelatedObjectsOrganization';
import {
    AddActivityResponse200RelatedObjectsOrganizationFromJSON,
    AddActivityResponse200RelatedObjectsOrganizationFromJSONTyped,
    AddActivityResponse200RelatedObjectsOrganizationToJSON,
} from './AddActivityResponse200RelatedObjectsOrganization';
import type { AddActivityResponse200RelatedObjectsPerson } from './AddActivityResponse200RelatedObjectsPerson';
import {
    AddActivityResponse200RelatedObjectsPersonFromJSON,
    AddActivityResponse200RelatedObjectsPersonFromJSONTyped,
    AddActivityResponse200RelatedObjectsPersonToJSON,
} from './AddActivityResponse200RelatedObjectsPerson';
import type { GetActivitiesResponse200RelatedObjectsUser } from './GetActivitiesResponse200RelatedObjectsUser';
import {
    GetActivitiesResponse200RelatedObjectsUserFromJSON,
    GetActivitiesResponse200RelatedObjectsUserFromJSONTyped,
    GetActivitiesResponse200RelatedObjectsUserToJSON,
} from './GetActivitiesResponse200RelatedObjectsUser';

/**
 * 
 * @export
 * @interface GetAssociatedDealsResponse200AllOfRelatedObjects
 */
export interface GetAssociatedDealsResponse200AllOfRelatedObjects {
    /**
     * 
     * @type {AddActivityResponse200RelatedObjectsOrganization}
     * @memberof GetAssociatedDealsResponse200AllOfRelatedObjects
     */
    organization?: AddActivityResponse200RelatedObjectsOrganization;
    /**
     * 
     * @type {AddActivityResponse200RelatedObjectsPerson}
     * @memberof GetAssociatedDealsResponse200AllOfRelatedObjects
     */
    person?: AddActivityResponse200RelatedObjectsPerson;
    /**
     * 
     * @type {GetActivitiesResponse200RelatedObjectsUser}
     * @memberof GetAssociatedDealsResponse200AllOfRelatedObjects
     */
    user?: GetActivitiesResponse200RelatedObjectsUser;
}

/**
 * Check if a given object implements the GetAssociatedDealsResponse200AllOfRelatedObjects interface.
 */
export function instanceOfGetAssociatedDealsResponse200AllOfRelatedObjects(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAssociatedDealsResponse200AllOfRelatedObjectsFromJSON(json: any): GetAssociatedDealsResponse200AllOfRelatedObjects {
    return GetAssociatedDealsResponse200AllOfRelatedObjectsFromJSONTyped(json, false);
}

export function GetAssociatedDealsResponse200AllOfRelatedObjectsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAssociatedDealsResponse200AllOfRelatedObjects {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organization': !exists(json, 'organization') ? undefined : AddActivityResponse200RelatedObjectsOrganizationFromJSON(json['organization']),
        'person': !exists(json, 'person') ? undefined : AddActivityResponse200RelatedObjectsPersonFromJSON(json['person']),
        'user': !exists(json, 'user') ? undefined : GetActivitiesResponse200RelatedObjectsUserFromJSON(json['user']),
    };
}

export function GetAssociatedDealsResponse200AllOfRelatedObjectsToJSON(value?: GetAssociatedDealsResponse200AllOfRelatedObjects | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organization': AddActivityResponse200RelatedObjectsOrganizationToJSON(value.organization),
        'person': AddActivityResponse200RelatedObjectsPersonToJSON(value.person),
        'user': GetActivitiesResponse200RelatedObjectsUserToJSON(value.user),
    };
}

