/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAssociatedPersonUpdatesResponse200AllOfDataInner
 */
export interface GetAssociatedPersonUpdatesResponse200AllOfDataInner {
    /**
     * The type of the person update. (Possible object types - personChange, note, activity, file)
     * @type {string}
     * @memberof GetAssociatedPersonUpdatesResponse200AllOfDataInner
     */
    object?: string;
    /**
     * The creation date and time of the update
     * @type {string}
     * @memberof GetAssociatedPersonUpdatesResponse200AllOfDataInner
     */
    timestamp?: string;
    /**
     * The data related to the update
     * @type {object}
     * @memberof GetAssociatedPersonUpdatesResponse200AllOfDataInner
     */
    data?: object;
}

/**
 * Check if a given object implements the GetAssociatedPersonUpdatesResponse200AllOfDataInner interface.
 */
export function instanceOfGetAssociatedPersonUpdatesResponse200AllOfDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAssociatedPersonUpdatesResponse200AllOfDataInnerFromJSON(json: any): GetAssociatedPersonUpdatesResponse200AllOfDataInner {
    return GetAssociatedPersonUpdatesResponse200AllOfDataInnerFromJSONTyped(json, false);
}

export function GetAssociatedPersonUpdatesResponse200AllOfDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAssociatedPersonUpdatesResponse200AllOfDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'object': !exists(json, 'object') ? undefined : json['object'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function GetAssociatedPersonUpdatesResponse200AllOfDataInnerToJSON(value?: GetAssociatedPersonUpdatesResponse200AllOfDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'object': value.object,
        'timestamp': value.timestamp,
        'data': value.data,
    };
}

