/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddActivityResponse200RelatedObjectsPerson } from './AddActivityResponse200RelatedObjectsPerson';
import {
    AddActivityResponse200RelatedObjectsPersonFromJSON,
    AddActivityResponse200RelatedObjectsPersonFromJSONTyped,
    AddActivityResponse200RelatedObjectsPersonToJSON,
} from './AddActivityResponse200RelatedObjectsPerson';
import type { GetActivitiesResponse200RelatedObjectsDeal } from './GetActivitiesResponse200RelatedObjectsDeal';
import {
    GetActivitiesResponse200RelatedObjectsDealFromJSON,
    GetActivitiesResponse200RelatedObjectsDealFromJSONTyped,
    GetActivitiesResponse200RelatedObjectsDealToJSON,
} from './GetActivitiesResponse200RelatedObjectsDeal';
import type { GetActivitiesResponse200RelatedObjectsOrganization } from './GetActivitiesResponse200RelatedObjectsOrganization';
import {
    GetActivitiesResponse200RelatedObjectsOrganizationFromJSON,
    GetActivitiesResponse200RelatedObjectsOrganizationFromJSONTyped,
    GetActivitiesResponse200RelatedObjectsOrganizationToJSON,
} from './GetActivitiesResponse200RelatedObjectsOrganization';
import type { GetActivitiesResponse200RelatedObjectsUser } from './GetActivitiesResponse200RelatedObjectsUser';
import {
    GetActivitiesResponse200RelatedObjectsUserFromJSON,
    GetActivitiesResponse200RelatedObjectsUserFromJSONTyped,
    GetActivitiesResponse200RelatedObjectsUserToJSON,
} from './GetActivitiesResponse200RelatedObjectsUser';

/**
 * 
 * @export
 * @interface GetDealUpdatesResponse200AllOfRelatedObjects
 */
export interface GetDealUpdatesResponse200AllOfRelatedObjects {
    /**
     * 
     * @type {GetActivitiesResponse200RelatedObjectsDeal}
     * @memberof GetDealUpdatesResponse200AllOfRelatedObjects
     */
    deal?: GetActivitiesResponse200RelatedObjectsDeal;
    /**
     * 
     * @type {GetActivitiesResponse200RelatedObjectsOrganization}
     * @memberof GetDealUpdatesResponse200AllOfRelatedObjects
     */
    organization?: GetActivitiesResponse200RelatedObjectsOrganization;
    /**
     * 
     * @type {GetActivitiesResponse200RelatedObjectsUser}
     * @memberof GetDealUpdatesResponse200AllOfRelatedObjects
     */
    user?: GetActivitiesResponse200RelatedObjectsUser;
    /**
     * 
     * @type {AddActivityResponse200RelatedObjectsPerson}
     * @memberof GetDealUpdatesResponse200AllOfRelatedObjects
     */
    person?: AddActivityResponse200RelatedObjectsPerson;
}

/**
 * Check if a given object implements the GetDealUpdatesResponse200AllOfRelatedObjects interface.
 */
export function instanceOfGetDealUpdatesResponse200AllOfRelatedObjects(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetDealUpdatesResponse200AllOfRelatedObjectsFromJSON(json: any): GetDealUpdatesResponse200AllOfRelatedObjects {
    return GetDealUpdatesResponse200AllOfRelatedObjectsFromJSONTyped(json, false);
}

export function GetDealUpdatesResponse200AllOfRelatedObjectsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDealUpdatesResponse200AllOfRelatedObjects {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deal': !exists(json, 'deal') ? undefined : GetActivitiesResponse200RelatedObjectsDealFromJSON(json['deal']),
        'organization': !exists(json, 'organization') ? undefined : GetActivitiesResponse200RelatedObjectsOrganizationFromJSON(json['organization']),
        'user': !exists(json, 'user') ? undefined : GetActivitiesResponse200RelatedObjectsUserFromJSON(json['user']),
        'person': !exists(json, 'person') ? undefined : AddActivityResponse200RelatedObjectsPersonFromJSON(json['person']),
    };
}

export function GetDealUpdatesResponse200AllOfRelatedObjectsToJSON(value?: GetDealUpdatesResponse200AllOfRelatedObjects | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deal': GetActivitiesResponse200RelatedObjectsDealToJSON(value.deal),
        'organization': GetActivitiesResponse200RelatedObjectsOrganizationToJSON(value.organization),
        'user': GetActivitiesResponse200RelatedObjectsUserToJSON(value.user),
        'person': AddActivityResponse200RelatedObjectsPersonToJSON(value.person),
    };
}

