/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaginationDetails } from './PaginationDetails';
import {
    PaginationDetailsFromJSON,
    PaginationDetailsFromJSONTyped,
    PaginationDetailsToJSON,
} from './PaginationDetails';

/**
 * 
 * @export
 * @interface GetFilesResponse200AdditionalData
 */
export interface GetFilesResponse200AdditionalData {
    /**
     * 
     * @type {PaginationDetails}
     * @memberof GetFilesResponse200AdditionalData
     */
    pagination?: PaginationDetails;
}

/**
 * Check if a given object implements the GetFilesResponse200AdditionalData interface.
 */
export function instanceOfGetFilesResponse200AdditionalData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetFilesResponse200AdditionalDataFromJSON(json: any): GetFilesResponse200AdditionalData {
    return GetFilesResponse200AdditionalDataFromJSONTyped(json, false);
}

export function GetFilesResponse200AdditionalDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFilesResponse200AdditionalData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': !exists(json, 'pagination') ? undefined : PaginationDetailsFromJSON(json['pagination']),
    };
}

export function GetFilesResponse200AdditionalDataToJSON(value?: GetFilesResponse200AdditionalData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pagination': PaginationDetailsToJSON(value.pagination),
    };
}

