/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The deal this note is attached to
 * @export
 * @interface GetNotesResponse200DataInnerDeal
 */
export interface GetNotesResponse200DataInnerDeal {
    /**
     * The title of the deal this note is attached to
     * @type {string}
     * @memberof GetNotesResponse200DataInnerDeal
     */
    title?: string;
}

/**
 * Check if a given object implements the GetNotesResponse200DataInnerDeal interface.
 */
export function instanceOfGetNotesResponse200DataInnerDeal(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetNotesResponse200DataInnerDealFromJSON(json: any): GetNotesResponse200DataInnerDeal {
    return GetNotesResponse200DataInnerDealFromJSONTyped(json, false);
}

export function GetNotesResponse200DataInnerDealFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNotesResponse200DataInnerDeal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
    };
}

export function GetNotesResponse200DataInnerDealToJSON(value?: GetNotesResponse200DataInnerDeal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
    };
}

