/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The pagination details of the list
 * @export
 * @interface GetNotesResponse200AdditionalDataPagination
 */
export interface GetNotesResponse200AdditionalDataPagination {
    /**
     * Pagination start
     * @type {number}
     * @memberof GetNotesResponse200AdditionalDataPagination
     */
    start?: number;
    /**
     * Items shown per page
     * @type {number}
     * @memberof GetNotesResponse200AdditionalDataPagination
     */
    limit?: number;
    /**
     * If there are more list items in the collection than displayed or not
     * @type {boolean}
     * @memberof GetNotesResponse200AdditionalDataPagination
     */
    more_items_in_collection?: boolean;
    /**
     * Next pagination start
     * @type {number}
     * @memberof GetNotesResponse200AdditionalDataPagination
     */
    next_start?: number;
}

/**
 * Check if a given object implements the GetNotesResponse200AdditionalDataPagination interface.
 */
export function instanceOfGetNotesResponse200AdditionalDataPagination(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetNotesResponse200AdditionalDataPaginationFromJSON(json: any): GetNotesResponse200AdditionalDataPagination {
    return GetNotesResponse200AdditionalDataPaginationFromJSONTyped(json, false);
}

export function GetNotesResponse200AdditionalDataPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNotesResponse200AdditionalDataPagination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': !exists(json, 'start') ? undefined : json['start'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'more_items_in_collection': !exists(json, 'more_items_in_collection') ? undefined : json['more_items_in_collection'],
        'next_start': !exists(json, 'next_start') ? undefined : json['next_start'],
    };
}

export function GetNotesResponse200AdditionalDataPaginationToJSON(value?: GetNotesResponse200AdditionalDataPagination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start,
        'limit': value.limit,
        'more_items_in_collection': value.more_items_in_collection,
        'next_start': value.next_start,
    };
}

