/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetNotesResponse200DataInnerDeal } from './GetNotesResponse200DataInnerDeal';
import {
    GetNotesResponse200DataInnerDealFromJSON,
    GetNotesResponse200DataInnerDealFromJSONTyped,
    GetNotesResponse200DataInnerDealToJSON,
} from './GetNotesResponse200DataInnerDeal';
import type { GetNotesResponse200DataInnerOrganization } from './GetNotesResponse200DataInnerOrganization';
import {
    GetNotesResponse200DataInnerOrganizationFromJSON,
    GetNotesResponse200DataInnerOrganizationFromJSONTyped,
    GetNotesResponse200DataInnerOrganizationToJSON,
} from './GetNotesResponse200DataInnerOrganization';
import type { GetNotesResponse200DataInnerPerson } from './GetNotesResponse200DataInnerPerson';
import {
    GetNotesResponse200DataInnerPersonFromJSON,
    GetNotesResponse200DataInnerPersonFromJSONTyped,
    GetNotesResponse200DataInnerPersonToJSON,
} from './GetNotesResponse200DataInnerPerson';
import type { GetNotesResponse200DataInnerUser } from './GetNotesResponse200DataInnerUser';
import {
    GetNotesResponse200DataInnerUserFromJSON,
    GetNotesResponse200DataInnerUserFromJSONTyped,
    GetNotesResponse200DataInnerUserToJSON,
} from './GetNotesResponse200DataInnerUser';

/**
 * 
 * @export
 * @interface GetNotesResponse200DataInner
 */
export interface GetNotesResponse200DataInner {
    /**
     * The ID of the note
     * @type {number}
     * @memberof GetNotesResponse200DataInner
     */
    id?: number;
    /**
     * Whether the note is active or deleted
     * @type {boolean}
     * @memberof GetNotesResponse200DataInner
     */
    active_flag?: boolean;
    /**
     * The creation date and time of the note
     * @type {string}
     * @memberof GetNotesResponse200DataInner
     */
    add_time?: string;
    /**
     * The content of the note in HTML format. Subject to sanitization on the back-end.
     * @type {string}
     * @memberof GetNotesResponse200DataInner
     */
    content?: string;
    /**
     * 
     * @type {GetNotesResponse200DataInnerDeal}
     * @memberof GetNotesResponse200DataInner
     */
    deal?: GetNotesResponse200DataInnerDeal;
    /**
     * The ID of the lead the note is attached to
     * @type {string}
     * @memberof GetNotesResponse200DataInner
     */
    lead_id?: string;
    /**
     * The ID of the deal the note is attached to
     * @type {number}
     * @memberof GetNotesResponse200DataInner
     */
    deal_id?: number;
    /**
     * The ID of the user who last updated the note
     * @type {number}
     * @memberof GetNotesResponse200DataInner
     */
    last_update_user_id?: number;
    /**
     * The ID of the organization the note is attached to
     * @type {number}
     * @memberof GetNotesResponse200DataInner
     */
    org_id?: number;
    /**
     * 
     * @type {GetNotesResponse200DataInnerOrganization}
     * @memberof GetNotesResponse200DataInner
     */
    organization?: GetNotesResponse200DataInnerOrganization;
    /**
     * 
     * @type {GetNotesResponse200DataInnerPerson}
     * @memberof GetNotesResponse200DataInner
     */
    person?: GetNotesResponse200DataInnerPerson;
    /**
     * The ID of the person the note is attached to
     * @type {number}
     * @memberof GetNotesResponse200DataInner
     */
    person_id?: number;
    /**
     * If true, the results are filtered by note to deal pinning state
     * @type {boolean}
     * @memberof GetNotesResponse200DataInner
     */
    pinned_to_deal_flag?: boolean;
    /**
     * If true, the results are filtered by note to organization pinning state
     * @type {boolean}
     * @memberof GetNotesResponse200DataInner
     */
    pinned_to_organization_flag?: boolean;
    /**
     * If true, the results are filtered by note to person pinning state
     * @type {boolean}
     * @memberof GetNotesResponse200DataInner
     */
    pinned_to_person_flag?: boolean;
    /**
     * The last updated date and time of the note
     * @type {string}
     * @memberof GetNotesResponse200DataInner
     */
    update_time?: string;
    /**
     * 
     * @type {GetNotesResponse200DataInnerUser}
     * @memberof GetNotesResponse200DataInner
     */
    user?: GetNotesResponse200DataInnerUser;
    /**
     * The ID of the note creator
     * @type {number}
     * @memberof GetNotesResponse200DataInner
     */
    user_id?: number;
}

/**
 * Check if a given object implements the GetNotesResponse200DataInner interface.
 */
export function instanceOfGetNotesResponse200DataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetNotesResponse200DataInnerFromJSON(json: any): GetNotesResponse200DataInner {
    return GetNotesResponse200DataInnerFromJSONTyped(json, false);
}

export function GetNotesResponse200DataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNotesResponse200DataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'active_flag': !exists(json, 'active_flag') ? undefined : json['active_flag'],
        'add_time': !exists(json, 'add_time') ? undefined : json['add_time'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'deal': !exists(json, 'deal') ? undefined : GetNotesResponse200DataInnerDealFromJSON(json['deal']),
        'lead_id': !exists(json, 'lead_id') ? undefined : json['lead_id'],
        'deal_id': !exists(json, 'deal_id') ? undefined : json['deal_id'],
        'last_update_user_id': !exists(json, 'last_update_user_id') ? undefined : json['last_update_user_id'],
        'org_id': !exists(json, 'org_id') ? undefined : json['org_id'],
        'organization': !exists(json, 'organization') ? undefined : GetNotesResponse200DataInnerOrganizationFromJSON(json['organization']),
        'person': !exists(json, 'person') ? undefined : GetNotesResponse200DataInnerPersonFromJSON(json['person']),
        'person_id': !exists(json, 'person_id') ? undefined : json['person_id'],
        'pinned_to_deal_flag': !exists(json, 'pinned_to_deal_flag') ? undefined : json['pinned_to_deal_flag'],
        'pinned_to_organization_flag': !exists(json, 'pinned_to_organization_flag') ? undefined : json['pinned_to_organization_flag'],
        'pinned_to_person_flag': !exists(json, 'pinned_to_person_flag') ? undefined : json['pinned_to_person_flag'],
        'update_time': !exists(json, 'update_time') ? undefined : json['update_time'],
        'user': !exists(json, 'user') ? undefined : GetNotesResponse200DataInnerUserFromJSON(json['user']),
        'user_id': !exists(json, 'user_id') ? undefined : json['user_id'],
    };
}

export function GetNotesResponse200DataInnerToJSON(value?: GetNotesResponse200DataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'active_flag': value.active_flag,
        'add_time': value.add_time,
        'content': value.content,
        'deal': GetNotesResponse200DataInnerDealToJSON(value.deal),
        'lead_id': value.lead_id,
        'deal_id': value.deal_id,
        'last_update_user_id': value.last_update_user_id,
        'org_id': value.org_id,
        'organization': GetNotesResponse200DataInnerOrganizationToJSON(value.organization),
        'person': GetNotesResponse200DataInnerPersonToJSON(value.person),
        'person_id': value.person_id,
        'pinned_to_deal_flag': value.pinned_to_deal_flag,
        'pinned_to_organization_flag': value.pinned_to_organization_flag,
        'pinned_to_person_flag': value.pinned_to_person_flag,
        'update_time': value.update_time,
        'user': GetNotesResponse200DataInnerUserToJSON(value.user),
        'user_id': value.user_id,
    };
}

