/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetOrganizationResponse200AllOfAdditionalData } from './GetOrganizationResponse200AllOfAdditionalData';
import {
    GetOrganizationResponse200AllOfAdditionalDataFromJSON,
    GetOrganizationResponse200AllOfAdditionalDataFromJSONTyped,
    GetOrganizationResponse200AllOfAdditionalDataToJSON,
} from './GetOrganizationResponse200AllOfAdditionalData';
import type { GetOrganizationsResponse200AllOfRelatedObjects } from './GetOrganizationsResponse200AllOfRelatedObjects';
import {
    GetOrganizationsResponse200AllOfRelatedObjectsFromJSON,
    GetOrganizationsResponse200AllOfRelatedObjectsFromJSONTyped,
    GetOrganizationsResponse200AllOfRelatedObjectsToJSON,
} from './GetOrganizationsResponse200AllOfRelatedObjects';
import type { OrganizationItem } from './OrganizationItem';
import {
    OrganizationItemFromJSON,
    OrganizationItemFromJSONTyped,
    OrganizationItemToJSON,
} from './OrganizationItem';

/**
 * 
 * @export
 * @interface GetOrganizationResponse200
 */
export interface GetOrganizationResponse200 {
    /**
     * If the response is successful or not
     * @type {boolean}
     * @memberof GetOrganizationResponse200
     */
    success?: boolean;
    /**
     * 
     * @type {OrganizationItem}
     * @memberof GetOrganizationResponse200
     */
    data?: OrganizationItem;
    /**
     * 
     * @type {GetOrganizationResponse200AllOfAdditionalData}
     * @memberof GetOrganizationResponse200
     */
    additional_data?: GetOrganizationResponse200AllOfAdditionalData;
    /**
     * 
     * @type {GetOrganizationsResponse200AllOfRelatedObjects}
     * @memberof GetOrganizationResponse200
     */
    related_objects?: GetOrganizationsResponse200AllOfRelatedObjects;
}

/**
 * Check if a given object implements the GetOrganizationResponse200 interface.
 */
export function instanceOfGetOrganizationResponse200(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetOrganizationResponse200FromJSON(json: any): GetOrganizationResponse200 {
    return GetOrganizationResponse200FromJSONTyped(json, false);
}

export function GetOrganizationResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrganizationResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : OrganizationItemFromJSON(json['data']),
        'additional_data': !exists(json, 'additional_data') ? undefined : GetOrganizationResponse200AllOfAdditionalDataFromJSON(json['additional_data']),
        'related_objects': !exists(json, 'related_objects') ? undefined : GetOrganizationsResponse200AllOfRelatedObjectsFromJSON(json['related_objects']),
    };
}

export function GetOrganizationResponse200ToJSON(value?: GetOrganizationResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'data': OrganizationItemToJSON(value.data),
        'additional_data': GetOrganizationResponse200AllOfAdditionalDataToJSON(value.additional_data),
        'related_objects': GetOrganizationsResponse200AllOfRelatedObjectsToJSON(value.related_objects),
    };
}

