/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetActivitiesResponse200AdditionalData } from './GetActivitiesResponse200AdditionalData';
import {
    GetActivitiesResponse200AdditionalDataFromJSON,
    GetActivitiesResponse200AdditionalDataFromJSONTyped,
    GetActivitiesResponse200AdditionalDataToJSON,
} from './GetActivitiesResponse200AdditionalData';
import type { GetPersonProductsResponse200AllOfDataInner } from './GetPersonProductsResponse200AllOfDataInner';
import {
    GetPersonProductsResponse200AllOfDataInnerFromJSON,
    GetPersonProductsResponse200AllOfDataInnerFromJSONTyped,
    GetPersonProductsResponse200AllOfDataInnerToJSON,
} from './GetPersonProductsResponse200AllOfDataInner';

/**
 * 
 * @export
 * @interface GetPersonProductsResponse200
 */
export interface GetPersonProductsResponse200 {
    /**
     * If the response is successful or not
     * @type {boolean}
     * @memberof GetPersonProductsResponse200
     */
    success?: boolean;
    /**
     * The array of deal products
     * @type {Array<GetPersonProductsResponse200AllOfDataInner>}
     * @memberof GetPersonProductsResponse200
     */
    data?: Array<GetPersonProductsResponse200AllOfDataInner>;
    /**
     * 
     * @type {GetActivitiesResponse200AdditionalData}
     * @memberof GetPersonProductsResponse200
     */
    additional_data?: GetActivitiesResponse200AdditionalData;
}

/**
 * Check if a given object implements the GetPersonProductsResponse200 interface.
 */
export function instanceOfGetPersonProductsResponse200(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPersonProductsResponse200FromJSON(json: any): GetPersonProductsResponse200 {
    return GetPersonProductsResponse200FromJSONTyped(json, false);
}

export function GetPersonProductsResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPersonProductsResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(GetPersonProductsResponse200AllOfDataInnerFromJSON)),
        'additional_data': !exists(json, 'additional_data') ? undefined : GetActivitiesResponse200AdditionalDataFromJSON(json['additional_data']),
    };
}

export function GetPersonProductsResponse200ToJSON(value?: GetPersonProductsResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(GetPersonProductsResponse200AllOfDataInnerToJSON)),
        'additional_data': GetActivitiesResponse200AdditionalDataToJSON(value.additional_data),
    };
}

