/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The formatted values of the deals
 * @export
 * @interface GetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValues
 */
export interface GetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValues {
    /**
     * The formatted values of the deals
     * @type {string}
     * @memberof GetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValues
     */
    CURRENCY_ID?: string;
}

/**
 * Check if a given object implements the GetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValues interface.
 */
export function instanceOfGetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValues(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValuesFromJSON(json: any): GetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValues {
    return GetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValuesFromJSONTyped(json, false);
}

export function GetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValues {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CURRENCY_ID': !exists(json, 'CURRENCY_ID') ? undefined : json['CURRENCY_ID'],
    };
}

export function GetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValuesToJSON(value?: GetPipelineMovementStatisticsResponse200AllOfDataNewDealsFormattedValues | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CURRENCY_ID': value.CURRENCY_ID,
    };
}

