/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetPermissionSetsResponse200AllOfDataInner } from './GetPermissionSetsResponse200AllOfDataInner';
import {
    GetPermissionSetsResponse200AllOfDataInnerFromJSON,
    GetPermissionSetsResponse200AllOfDataInnerFromJSONTyped,
    GetPermissionSetsResponse200AllOfDataInnerToJSON,
} from './GetPermissionSetsResponse200AllOfDataInner';

/**
 * 
 * @export
 * @interface GetPermissionSetsResponse200AllOf
 */
export interface GetPermissionSetsResponse200AllOf {
    /**
     * The array of permission set
     * @type {Array<GetPermissionSetsResponse200AllOfDataInner>}
     * @memberof GetPermissionSetsResponse200AllOf
     */
    data?: Array<GetPermissionSetsResponse200AllOfDataInner>;
}

/**
 * Check if a given object implements the GetPermissionSetsResponse200AllOf interface.
 */
export function instanceOfGetPermissionSetsResponse200AllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPermissionSetsResponse200AllOfFromJSON(json: any): GetPermissionSetsResponse200AllOf {
    return GetPermissionSetsResponse200AllOfFromJSONTyped(json, false);
}

export function GetPermissionSetsResponse200AllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPermissionSetsResponse200AllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(GetPermissionSetsResponse200AllOfDataInnerFromJSON)),
    };
}

export function GetPermissionSetsResponse200AllOfToJSON(value?: GetPermissionSetsResponse200AllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(GetPermissionSetsResponse200AllOfDataInnerToJSON)),
    };
}

