/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetproductResponse200DataAllOf
 */
export interface GetproductResponse200DataAllOf {
    /**
     * Array of objects, each containing: currency (string), price (number), cost (number, optional), overhead_cost (number, optional)
     * @type {Array<object>}
     * @memberof GetproductResponse200DataAllOf
     */
    prices?: Array<object>;
}

/**
 * Check if a given object implements the GetproductResponse200DataAllOf interface.
 */
export function instanceOfGetproductResponse200DataAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetproductResponse200DataAllOfFromJSON(json: any): GetproductResponse200DataAllOf {
    return GetproductResponse200DataAllOfFromJSONTyped(json, false);
}

export function GetproductResponse200DataAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetproductResponse200DataAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prices': !exists(json, 'prices') ? undefined : json['prices'],
    };
}

export function GetproductResponse200DataAllOfToJSON(value?: GetproductResponse200DataAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prices': value.prices,
    };
}

