/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetAssociatedFilesResponse200AllOfDataInner } from './GetAssociatedFilesResponse200AllOfDataInner';
import {
    GetAssociatedFilesResponse200AllOfDataInnerFromJSON,
    GetAssociatedFilesResponse200AllOfDataInnerFromJSONTyped,
    GetAssociatedFilesResponse200AllOfDataInnerToJSON,
} from './GetAssociatedFilesResponse200AllOfDataInner';

/**
 * 
 * @export
 * @interface GetRecentsResponse200DataInnerAnyOf3
 */
export interface GetRecentsResponse200DataInnerAnyOf3 {
    /**
     * 
     * @type {string}
     * @memberof GetRecentsResponse200DataInnerAnyOf3
     */
    item?: GetRecentsResponse200DataInnerAnyOf3ItemEnum;
    /**
     * 
     * @type {number}
     * @memberof GetRecentsResponse200DataInnerAnyOf3
     */
    id?: number;
    /**
     * 
     * @type {GetAssociatedFilesResponse200AllOfDataInner}
     * @memberof GetRecentsResponse200DataInnerAnyOf3
     */
    data?: GetAssociatedFilesResponse200AllOfDataInner;
}

/**
* @export
* @enum {string}
*/
export enum GetRecentsResponse200DataInnerAnyOf3ItemEnum {
    File = 'file'
}


/**
 * Check if a given object implements the GetRecentsResponse200DataInnerAnyOf3 interface.
 */
export function instanceOfGetRecentsResponse200DataInnerAnyOf3(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetRecentsResponse200DataInnerAnyOf3FromJSON(json: any): GetRecentsResponse200DataInnerAnyOf3 {
    return GetRecentsResponse200DataInnerAnyOf3FromJSONTyped(json, false);
}

export function GetRecentsResponse200DataInnerAnyOf3FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRecentsResponse200DataInnerAnyOf3 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': !exists(json, 'item') ? undefined : json['item'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'data': !exists(json, 'data') ? undefined : GetAssociatedFilesResponse200AllOfDataInnerFromJSON(json['data']),
    };
}

export function GetRecentsResponse200DataInnerAnyOf3ToJSON(value?: GetRecentsResponse200DataInnerAnyOf3 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': value.item,
        'id': value.id,
        'data': GetAssociatedFilesResponse200AllOfDataInnerToJSON(value.data),
    };
}

