/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseOrganizationItem } from './BaseOrganizationItem';
import {
    BaseOrganizationItemFromJSON,
    BaseOrganizationItemFromJSONTyped,
    BaseOrganizationItemToJSON,
} from './BaseOrganizationItem';

/**
 * 
 * @export
 * @interface GetRecentsResponse200DataInnerAnyOf7
 */
export interface GetRecentsResponse200DataInnerAnyOf7 {
    /**
     * 
     * @type {string}
     * @memberof GetRecentsResponse200DataInnerAnyOf7
     */
    item?: GetRecentsResponse200DataInnerAnyOf7ItemEnum;
    /**
     * 
     * @type {number}
     * @memberof GetRecentsResponse200DataInnerAnyOf7
     */
    id?: number;
    /**
     * 
     * @type {BaseOrganizationItem}
     * @memberof GetRecentsResponse200DataInnerAnyOf7
     */
    data?: BaseOrganizationItem;
}

/**
* @export
* @enum {string}
*/
export enum GetRecentsResponse200DataInnerAnyOf7ItemEnum {
    Organization = 'organization'
}


/**
 * Check if a given object implements the GetRecentsResponse200DataInnerAnyOf7 interface.
 */
export function instanceOfGetRecentsResponse200DataInnerAnyOf7(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetRecentsResponse200DataInnerAnyOf7FromJSON(json: any): GetRecentsResponse200DataInnerAnyOf7 {
    return GetRecentsResponse200DataInnerAnyOf7FromJSONTyped(json, false);
}

export function GetRecentsResponse200DataInnerAnyOf7FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRecentsResponse200DataInnerAnyOf7 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': !exists(json, 'item') ? undefined : json['item'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'data': !exists(json, 'data') ? undefined : BaseOrganizationItemFromJSON(json['data']),
    };
}

export function GetRecentsResponse200DataInnerAnyOf7ToJSON(value?: GetRecentsResponse200DataInnerAnyOf7 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': value.item,
        'id': value.id,
        'data': BaseOrganizationItemToJSON(value.data),
    };
}

