/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetRolesResponse200AllOfAdditionalDataPagination } from './GetRolesResponse200AllOfAdditionalDataPagination';
import {
    GetRolesResponse200AllOfAdditionalDataPaginationFromJSON,
    GetRolesResponse200AllOfAdditionalDataPaginationFromJSONTyped,
    GetRolesResponse200AllOfAdditionalDataPaginationToJSON,
} from './GetRolesResponse200AllOfAdditionalDataPagination';

/**
 * The additional data in the role list
 * @export
 * @interface GetRolesResponse200AllOfAdditionalData
 */
export interface GetRolesResponse200AllOfAdditionalData {
    /**
     * 
     * @type {GetRolesResponse200AllOfAdditionalDataPagination}
     * @memberof GetRolesResponse200AllOfAdditionalData
     */
    pagination?: GetRolesResponse200AllOfAdditionalDataPagination;
}

/**
 * Check if a given object implements the GetRolesResponse200AllOfAdditionalData interface.
 */
export function instanceOfGetRolesResponse200AllOfAdditionalData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetRolesResponse200AllOfAdditionalDataFromJSON(json: any): GetRolesResponse200AllOfAdditionalData {
    return GetRolesResponse200AllOfAdditionalDataFromJSONTyped(json, false);
}

export function GetRolesResponse200AllOfAdditionalDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRolesResponse200AllOfAdditionalData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': !exists(json, 'pagination') ? undefined : GetRolesResponse200AllOfAdditionalDataPaginationFromJSON(json['pagination']),
    };
}

export function GetRolesResponse200AllOfAdditionalDataToJSON(value?: GetRolesResponse200AllOfAdditionalData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pagination': GetRolesResponse200AllOfAdditionalDataPaginationToJSON(value.pagination),
    };
}

