/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserSettingsResponse200AllOfData
 */
export interface GetUserSettingsResponse200AllOfData {
    /**
     * If the vendors are allowed to install custom Marketplace apps with functionality and content in the Pipedrive UI or not
     * @type {boolean}
     * @memberof GetUserSettingsResponse200AllOfData
     */
    marketplace_allow_custom_install_url?: boolean;
    /**
     * If the vendors are allowed to extend their Marketplace apps with functionality and content in the Pipedrive UI or not
     * @type {boolean}
     * @memberof GetUserSettingsResponse200AllOfData
     */
    marketplace_app_extensions_vendor?: boolean;
    /**
     * If the vendors are allowed to be part of the Marketplace team or not
     * @type {boolean}
     * @memberof GetUserSettingsResponse200AllOfData
     */
    marketplace_team?: boolean;
    /**
     * The number of results shown in list by default
     * @type {number}
     * @memberof GetUserSettingsResponse200AllOfData
     */
    list_limit?: number;
    /**
     * Whether beta app is enabled
     * @type {boolean}
     * @memberof GetUserSettingsResponse200AllOfData
     */
    beta_app?: boolean;
    /**
     * Prevent salesphone call to override
     * @type {boolean}
     * @memberof GetUserSettingsResponse200AllOfData
     */
    prevent_salesphone_callto_override?: boolean;
    /**
     * The destination of file upload
     * @type {string}
     * @memberof GetUserSettingsResponse200AllOfData
     */
    file_upload_destination?: string;
    /**
     * The call to link syntax
     * @type {string}
     * @memberof GetUserSettingsResponse200AllOfData
     */
    callto_link_syntax?: string;
    /**
     * Whether the expected close date of the deal is filled automatically or not
     * @type {boolean}
     * @memberof GetUserSettingsResponse200AllOfData
     */
    autofill_deal_expected_close_date?: boolean;
    /**
     * Allow the vendors to duplicate a person
     * @type {string}
     * @memberof GetUserSettingsResponse200AllOfData
     */
    person_duplicate_condition?: string;
}

/**
 * Check if a given object implements the GetUserSettingsResponse200AllOfData interface.
 */
export function instanceOfGetUserSettingsResponse200AllOfData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetUserSettingsResponse200AllOfDataFromJSON(json: any): GetUserSettingsResponse200AllOfData {
    return GetUserSettingsResponse200AllOfDataFromJSONTyped(json, false);
}

export function GetUserSettingsResponse200AllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserSettingsResponse200AllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'marketplace_allow_custom_install_url': !exists(json, 'marketplace_allow_custom_install_url') ? undefined : json['marketplace_allow_custom_install_url'],
        'marketplace_app_extensions_vendor': !exists(json, 'marketplace_app_extensions_vendor') ? undefined : json['marketplace_app_extensions_vendor'],
        'marketplace_team': !exists(json, 'marketplace_team') ? undefined : json['marketplace_team'],
        'list_limit': !exists(json, 'list_limit') ? undefined : json['list_limit'],
        'beta_app': !exists(json, 'beta_app') ? undefined : json['beta_app'],
        'prevent_salesphone_callto_override': !exists(json, 'prevent_salesphone_callto_override') ? undefined : json['prevent_salesphone_callto_override'],
        'file_upload_destination': !exists(json, 'file_upload_destination') ? undefined : json['file_upload_destination'],
        'callto_link_syntax': !exists(json, 'callto_link_syntax') ? undefined : json['callto_link_syntax'],
        'autofill_deal_expected_close_date': !exists(json, 'autofill_deal_expected_close_date') ? undefined : json['autofill_deal_expected_close_date'],
        'person_duplicate_condition': !exists(json, 'person_duplicate_condition') ? undefined : json['person_duplicate_condition'],
    };
}

export function GetUserSettingsResponse200AllOfDataToJSON(value?: GetUserSettingsResponse200AllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'marketplace_allow_custom_install_url': value.marketplace_allow_custom_install_url,
        'marketplace_app_extensions_vendor': value.marketplace_app_extensions_vendor,
        'marketplace_team': value.marketplace_team,
        'list_limit': value.list_limit,
        'beta_app': value.beta_app,
        'prevent_salesphone_callto_override': value.prevent_salesphone_callto_override,
        'file_upload_destination': value.file_upload_destination,
        'callto_link_syntax': value.callto_link_syntax,
        'autofill_deal_expected_close_date': value.autofill_deal_expected_close_date,
        'person_duplicate_condition': value.person_duplicate_condition,
    };
}

