/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailMessageItemForListAllOfFromInner
 */
export interface MailMessageItemForListAllOfFromInner {
    /**
     * ID of the mail participant
     * @type {number}
     * @memberof MailMessageItemForListAllOfFromInner
     */
    id?: number;
    /**
     * Mail address of the mail participant
     * @type {string}
     * @memberof MailMessageItemForListAllOfFromInner
     */
    email_address?: string;
    /**
     * Name of the mail participant
     * @type {string}
     * @memberof MailMessageItemForListAllOfFromInner
     */
    name?: string;
    /**
     * ID of the linked person to the mail message
     * @type {number}
     * @memberof MailMessageItemForListAllOfFromInner
     */
    linked_person_id?: number;
    /**
     * Name of the linked person to the mail message
     * @type {string}
     * @memberof MailMessageItemForListAllOfFromInner
     */
    linked_person_name?: string;
    /**
     * ID of the mail message participant
     * @type {number}
     * @memberof MailMessageItemForListAllOfFromInner
     */
    mail_message_party_id?: number;
}

/**
 * Check if a given object implements the MailMessageItemForListAllOfFromInner interface.
 */
export function instanceOfMailMessageItemForListAllOfFromInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MailMessageItemForListAllOfFromInnerFromJSON(json: any): MailMessageItemForListAllOfFromInner {
    return MailMessageItemForListAllOfFromInnerFromJSONTyped(json, false);
}

export function MailMessageItemForListAllOfFromInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailMessageItemForListAllOfFromInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email_address': !exists(json, 'email_address') ? undefined : json['email_address'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'linked_person_id': !exists(json, 'linked_person_id') ? undefined : json['linked_person_id'],
        'linked_person_name': !exists(json, 'linked_person_name') ? undefined : json['linked_person_name'],
        'mail_message_party_id': !exists(json, 'mail_message_party_id') ? undefined : json['mail_message_party_id'],
    };
}

export function MailMessageItemForListAllOfFromInnerToJSON(value?: MailMessageItemForListAllOfFromInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email_address': value.email_address,
        'name': value.name,
        'linked_person_id': value.linked_person_id,
        'linked_person_name': value.linked_person_name,
        'mail_message_party_id': value.mail_message_party_id,
    };
}

