/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonCountEmailDealAndActivityInfo
 */
export interface PersonCountEmailDealAndActivityInfo {
    /**
     * The count of email messages related to the person
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    email_messages_count?: number;
    /**
     * The count of activities related to the person
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    activities_count?: number;
    /**
     * The count of done activities related to the person
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    done_activities_count?: number;
    /**
     * The count of undone activities related to the person
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    undone_activities_count?: number;
    /**
     * The count of files related to the person
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    files_count?: number;
    /**
     * The count of notes related to the person
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    notes_count?: number;
    /**
     * The count of followers related to the person
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    followers_count?: number;
    /**
     * The date and time of the last incoming email associated with the person
     * @type {string}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    last_incoming_mail_time?: string;
    /**
     * The date and time of the last outgoing email associated with the person
     * @type {string}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    last_outgoing_mail_time?: string;
    /**
     * The count of open deals related with the item
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    open_deals_count?: number;
    /**
     * The count of related open deals related with the item
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    related_open_deals_count?: number;
    /**
     * The count of closed deals related with the item
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    closed_deals_count?: number;
    /**
     * The count of related closed deals related with the item
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    related_closed_deals_count?: number;
    /**
     * The count of won deals related with the item
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    won_deals_count?: number;
    /**
     * The count of related won deals related with the item
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    related_won_deals_count?: number;
    /**
     * The count of lost deals related with the item
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    lost_deals_count?: number;
    /**
     * The count of related lost deals related with the item
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    related_lost_deals_count?: number;
    /**
     * The date of the next activity associated with the deal
     * @type {string}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    next_activity_date?: string;
    /**
     * The time of the next activity associated with the deal
     * @type {string}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    next_activity_time?: string;
    /**
     * The ID of the next activity associated with the deal
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    next_activity_id?: number | null;
    /**
     * The ID of the last activity associated with the deal
     * @type {number}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    last_activity_id?: number | null;
    /**
     * The date of the last activity associated with the deal
     * @type {string}
     * @memberof PersonCountEmailDealAndActivityInfo
     */
    last_activity_date?: string | null;
}

/**
 * Check if a given object implements the PersonCountEmailDealAndActivityInfo interface.
 */
export function instanceOfPersonCountEmailDealAndActivityInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PersonCountEmailDealAndActivityInfoFromJSON(json: any): PersonCountEmailDealAndActivityInfo {
    return PersonCountEmailDealAndActivityInfoFromJSONTyped(json, false);
}

export function PersonCountEmailDealAndActivityInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonCountEmailDealAndActivityInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email_messages_count': !exists(json, 'email_messages_count') ? undefined : json['email_messages_count'],
        'activities_count': !exists(json, 'activities_count') ? undefined : json['activities_count'],
        'done_activities_count': !exists(json, 'done_activities_count') ? undefined : json['done_activities_count'],
        'undone_activities_count': !exists(json, 'undone_activities_count') ? undefined : json['undone_activities_count'],
        'files_count': !exists(json, 'files_count') ? undefined : json['files_count'],
        'notes_count': !exists(json, 'notes_count') ? undefined : json['notes_count'],
        'followers_count': !exists(json, 'followers_count') ? undefined : json['followers_count'],
        'last_incoming_mail_time': !exists(json, 'last_incoming_mail_time') ? undefined : json['last_incoming_mail_time'],
        'last_outgoing_mail_time': !exists(json, 'last_outgoing_mail_time') ? undefined : json['last_outgoing_mail_time'],
        'open_deals_count': !exists(json, 'open_deals_count') ? undefined : json['open_deals_count'],
        'related_open_deals_count': !exists(json, 'related_open_deals_count') ? undefined : json['related_open_deals_count'],
        'closed_deals_count': !exists(json, 'closed_deals_count') ? undefined : json['closed_deals_count'],
        'related_closed_deals_count': !exists(json, 'related_closed_deals_count') ? undefined : json['related_closed_deals_count'],
        'won_deals_count': !exists(json, 'won_deals_count') ? undefined : json['won_deals_count'],
        'related_won_deals_count': !exists(json, 'related_won_deals_count') ? undefined : json['related_won_deals_count'],
        'lost_deals_count': !exists(json, 'lost_deals_count') ? undefined : json['lost_deals_count'],
        'related_lost_deals_count': !exists(json, 'related_lost_deals_count') ? undefined : json['related_lost_deals_count'],
        'next_activity_date': !exists(json, 'next_activity_date') ? undefined : json['next_activity_date'],
        'next_activity_time': !exists(json, 'next_activity_time') ? undefined : json['next_activity_time'],
        'next_activity_id': !exists(json, 'next_activity_id') ? undefined : json['next_activity_id'],
        'last_activity_id': !exists(json, 'last_activity_id') ? undefined : json['last_activity_id'],
        'last_activity_date': !exists(json, 'last_activity_date') ? undefined : json['last_activity_date'],
    };
}

export function PersonCountEmailDealAndActivityInfoToJSON(value?: PersonCountEmailDealAndActivityInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email_messages_count': value.email_messages_count,
        'activities_count': value.activities_count,
        'done_activities_count': value.done_activities_count,
        'undone_activities_count': value.undone_activities_count,
        'files_count': value.files_count,
        'notes_count': value.notes_count,
        'followers_count': value.followers_count,
        'last_incoming_mail_time': value.last_incoming_mail_time,
        'last_outgoing_mail_time': value.last_outgoing_mail_time,
        'open_deals_count': value.open_deals_count,
        'related_open_deals_count': value.related_open_deals_count,
        'closed_deals_count': value.closed_deals_count,
        'related_closed_deals_count': value.related_closed_deals_count,
        'won_deals_count': value.won_deals_count,
        'related_won_deals_count': value.related_won_deals_count,
        'lost_deals_count': value.lost_deals_count,
        'related_lost_deals_count': value.related_lost_deals_count,
        'next_activity_date': value.next_activity_date,
        'next_activity_time': value.next_activity_time,
        'next_activity_id': value.next_activity_id,
        'last_activity_id': value.last_activity_id,
        'last_activity_date': value.last_activity_date,
    };
}

