/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetActivitiesResponse200AdditionalData } from './GetActivitiesResponse200AdditionalData';
import {
    GetActivitiesResponse200AdditionalDataFromJSON,
    GetActivitiesResponse200AdditionalDataFromJSONTyped,
    GetActivitiesResponse200AdditionalDataToJSON,
} from './GetActivitiesResponse200AdditionalData';
import type { SearchOrganizationResponse200AllOfData } from './SearchOrganizationResponse200AllOfData';
import {
    SearchOrganizationResponse200AllOfDataFromJSON,
    SearchOrganizationResponse200AllOfDataFromJSONTyped,
    SearchOrganizationResponse200AllOfDataToJSON,
} from './SearchOrganizationResponse200AllOfData';

/**
 * 
 * @export
 * @interface SearchOrganizationResponse200AllOf
 */
export interface SearchOrganizationResponse200AllOf {
    /**
     * 
     * @type {SearchOrganizationResponse200AllOfData}
     * @memberof SearchOrganizationResponse200AllOf
     */
    data?: SearchOrganizationResponse200AllOfData;
    /**
     * 
     * @type {GetActivitiesResponse200AdditionalData}
     * @memberof SearchOrganizationResponse200AllOf
     */
    additional_data?: GetActivitiesResponse200AdditionalData;
}

/**
 * Check if a given object implements the SearchOrganizationResponse200AllOf interface.
 */
export function instanceOfSearchOrganizationResponse200AllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchOrganizationResponse200AllOfFromJSON(json: any): SearchOrganizationResponse200AllOf {
    return SearchOrganizationResponse200AllOfFromJSONTyped(json, false);
}

export function SearchOrganizationResponse200AllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchOrganizationResponse200AllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : SearchOrganizationResponse200AllOfDataFromJSON(json['data']),
        'additional_data': !exists(json, 'additional_data') ? undefined : GetActivitiesResponse200AdditionalDataFromJSON(json['additional_data']),
    };
}

export function SearchOrganizationResponse200AllOfToJSON(value?: SearchOrganizationResponse200AllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': SearchOrganizationResponse200AllOfDataToJSON(value.data),
        'additional_data': GetActivitiesResponse200AdditionalDataToJSON(value.additional_data),
    };
}

