/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetActivitiesResponse200AdditionalData } from './GetActivitiesResponse200AdditionalData';
import {
    GetActivitiesResponse200AdditionalDataFromJSON,
    GetActivitiesResponse200AdditionalDataFromJSONTyped,
    GetActivitiesResponse200AdditionalDataToJSON,
} from './GetActivitiesResponse200AdditionalData';
import type { SearchPersonsResponse200AllOfData } from './SearchPersonsResponse200AllOfData';
import {
    SearchPersonsResponse200AllOfDataFromJSON,
    SearchPersonsResponse200AllOfDataFromJSONTyped,
    SearchPersonsResponse200AllOfDataToJSON,
} from './SearchPersonsResponse200AllOfData';

/**
 * 
 * @export
 * @interface SearchPersonsResponse200AllOf
 */
export interface SearchPersonsResponse200AllOf {
    /**
     * 
     * @type {SearchPersonsResponse200AllOfData}
     * @memberof SearchPersonsResponse200AllOf
     */
    data?: SearchPersonsResponse200AllOfData;
    /**
     * 
     * @type {GetActivitiesResponse200AdditionalData}
     * @memberof SearchPersonsResponse200AllOf
     */
    additional_data?: GetActivitiesResponse200AdditionalData;
}

/**
 * Check if a given object implements the SearchPersonsResponse200AllOf interface.
 */
export function instanceOfSearchPersonsResponse200AllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchPersonsResponse200AllOfFromJSON(json: any): SearchPersonsResponse200AllOf {
    return SearchPersonsResponse200AllOfFromJSONTyped(json, false);
}

export function SearchPersonsResponse200AllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPersonsResponse200AllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : SearchPersonsResponse200AllOfDataFromJSON(json['data']),
        'additional_data': !exists(json, 'additional_data') ? undefined : GetActivitiesResponse200AdditionalDataFromJSON(json['additional_data']),
    };
}

export function SearchPersonsResponse200AllOfToJSON(value?: SearchPersonsResponse200AllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': SearchPersonsResponse200AllOfDataToJSON(value.data),
        'additional_data': GetActivitiesResponse200AdditionalDataToJSON(value.additional_data),
    };
}

