/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SearchDealsResponse200AllOfDataItemsInnerItemOrganization } from './SearchDealsResponse200AllOfDataItemsInnerItemOrganization';
import {
    SearchDealsResponse200AllOfDataItemsInnerItemOrganizationFromJSON,
    SearchDealsResponse200AllOfDataItemsInnerItemOrganizationFromJSONTyped,
    SearchDealsResponse200AllOfDataItemsInnerItemOrganizationToJSON,
} from './SearchDealsResponse200AllOfDataItemsInnerItemOrganization';
import type { SearchDealsResponse200AllOfDataItemsInnerItemOwner } from './SearchDealsResponse200AllOfDataItemsInnerItemOwner';
import {
    SearchDealsResponse200AllOfDataItemsInnerItemOwnerFromJSON,
    SearchDealsResponse200AllOfDataItemsInnerItemOwnerFromJSONTyped,
    SearchDealsResponse200AllOfDataItemsInnerItemOwnerToJSON,
} from './SearchDealsResponse200AllOfDataItemsInnerItemOwner';
import type { SearchDealsResponse200AllOfDataItemsInnerItemPerson } from './SearchDealsResponse200AllOfDataItemsInnerItemPerson';
import {
    SearchDealsResponse200AllOfDataItemsInnerItemPersonFromJSON,
    SearchDealsResponse200AllOfDataItemsInnerItemPersonFromJSONTyped,
    SearchDealsResponse200AllOfDataItemsInnerItemPersonToJSON,
} from './SearchDealsResponse200AllOfDataItemsInnerItemPerson';
import type { SearchDealsResponse200AllOfDataItemsInnerItemStage } from './SearchDealsResponse200AllOfDataItemsInnerItemStage';
import {
    SearchDealsResponse200AllOfDataItemsInnerItemStageFromJSON,
    SearchDealsResponse200AllOfDataItemsInnerItemStageFromJSONTyped,
    SearchDealsResponse200AllOfDataItemsInnerItemStageToJSON,
} from './SearchDealsResponse200AllOfDataItemsInnerItemStage';

/**
 * 
 * @export
 * @interface SearchDealsResponse200AllOfDataItemsInnerItem
 */
export interface SearchDealsResponse200AllOfDataItemsInnerItem {
    /**
     * The ID of the deal
     * @type {number}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    id?: number;
    /**
     * The type of the item
     * @type {string}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    type?: string;
    /**
     * The title of the deal
     * @type {string}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    title?: string;
    /**
     * The value of the deal
     * @type {number}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    value?: number;
    /**
     * The currency of the deal
     * @type {string}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    currency?: string;
    /**
     * The status of the deal
     * @type {string}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    status?: string;
    /**
     * The visibility of the deal
     * @type {number}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    visible_to?: number;
    /**
     * 
     * @type {SearchDealsResponse200AllOfDataItemsInnerItemOwner}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    owner?: SearchDealsResponse200AllOfDataItemsInnerItemOwner;
    /**
     * 
     * @type {SearchDealsResponse200AllOfDataItemsInnerItemStage}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    stage?: SearchDealsResponse200AllOfDataItemsInnerItemStage;
    /**
     * 
     * @type {SearchDealsResponse200AllOfDataItemsInnerItemPerson}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    person?: SearchDealsResponse200AllOfDataItemsInnerItemPerson | null;
    /**
     * 
     * @type {SearchDealsResponse200AllOfDataItemsInnerItemOrganization}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    organization?: SearchDealsResponse200AllOfDataItemsInnerItemOrganization | null;
    /**
     * Custom fields
     * @type {Array<string>}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    custom_fields?: Array<string>;
    /**
     * An array of notes
     * @type {Array<string>}
     * @memberof SearchDealsResponse200AllOfDataItemsInnerItem
     */
    notes?: Array<string>;
}

/**
 * Check if a given object implements the SearchDealsResponse200AllOfDataItemsInnerItem interface.
 */
export function instanceOfSearchDealsResponse200AllOfDataItemsInnerItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchDealsResponse200AllOfDataItemsInnerItemFromJSON(json: any): SearchDealsResponse200AllOfDataItemsInnerItem {
    return SearchDealsResponse200AllOfDataItemsInnerItemFromJSONTyped(json, false);
}

export function SearchDealsResponse200AllOfDataItemsInnerItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchDealsResponse200AllOfDataItemsInnerItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'visible_to': !exists(json, 'visible_to') ? undefined : json['visible_to'],
        'owner': !exists(json, 'owner') ? undefined : SearchDealsResponse200AllOfDataItemsInnerItemOwnerFromJSON(json['owner']),
        'stage': !exists(json, 'stage') ? undefined : SearchDealsResponse200AllOfDataItemsInnerItemStageFromJSON(json['stage']),
        'person': !exists(json, 'person') ? undefined : SearchDealsResponse200AllOfDataItemsInnerItemPersonFromJSON(json['person']),
        'organization': !exists(json, 'organization') ? undefined : SearchDealsResponse200AllOfDataItemsInnerItemOrganizationFromJSON(json['organization']),
        'custom_fields': !exists(json, 'custom_fields') ? undefined : json['custom_fields'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function SearchDealsResponse200AllOfDataItemsInnerItemToJSON(value?: SearchDealsResponse200AllOfDataItemsInnerItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'title': value.title,
        'value': value.value,
        'currency': value.currency,
        'status': value.status,
        'visible_to': value.visible_to,
        'owner': SearchDealsResponse200AllOfDataItemsInnerItemOwnerToJSON(value.owner),
        'stage': SearchDealsResponse200AllOfDataItemsInnerItemStageToJSON(value.stage),
        'person': SearchDealsResponse200AllOfDataItemsInnerItemPersonToJSON(value.person),
        'organization': SearchDealsResponse200AllOfDataItemsInnerItemOrganizationToJSON(value.organization),
        'custom_fields': value.custom_fields,
        'notes': value.notes,
    };
}

