/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdatePipelineResponse200AllOfData } from './UpdatePipelineResponse200AllOfData';
import {
    UpdatePipelineResponse200AllOfDataFromJSON,
    UpdatePipelineResponse200AllOfDataFromJSONTyped,
    UpdatePipelineResponse200AllOfDataToJSON,
} from './UpdatePipelineResponse200AllOfData';

/**
 * 
 * @export
 * @interface UpdatePipelineResponse200AllOf
 */
export interface UpdatePipelineResponse200AllOf {
    /**
     * 
     * @type {UpdatePipelineResponse200AllOfData}
     * @memberof UpdatePipelineResponse200AllOf
     */
    data?: UpdatePipelineResponse200AllOfData;
}

/**
 * Check if a given object implements the UpdatePipelineResponse200AllOf interface.
 */
export function instanceOfUpdatePipelineResponse200AllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdatePipelineResponse200AllOfFromJSON(json: any): UpdatePipelineResponse200AllOf {
    return UpdatePipelineResponse200AllOfFromJSONTyped(json, false);
}

export function UpdatePipelineResponse200AllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePipelineResponse200AllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : UpdatePipelineResponse200AllOfDataFromJSON(json['data']),
    };
}

export function UpdatePipelineResponse200AllOfToJSON(value?: UpdatePipelineResponse200AllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UpdatePipelineResponse200AllOfDataToJSON(value.data),
    };
}

