/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseOrganizationItem } from './BaseOrganizationItem';
import {
    BaseOrganizationItemFromJSON,
    BaseOrganizationItemFromJSONTyped,
    BaseOrganizationItemToJSON,
} from './BaseOrganizationItem';
import type { GetOrganizationsResponse200AllOfRelatedObjects } from './GetOrganizationsResponse200AllOfRelatedObjects';
import {
    GetOrganizationsResponse200AllOfRelatedObjectsFromJSON,
    GetOrganizationsResponse200AllOfRelatedObjectsFromJSONTyped,
    GetOrganizationsResponse200AllOfRelatedObjectsToJSON,
} from './GetOrganizationsResponse200AllOfRelatedObjects';

/**
 * 
 * @export
 * @interface UpdateOrganizationResponse200
 */
export interface UpdateOrganizationResponse200 {
    /**
     * If the response is successful or not
     * @type {boolean}
     * @memberof UpdateOrganizationResponse200
     */
    success?: boolean;
    /**
     * 
     * @type {BaseOrganizationItem}
     * @memberof UpdateOrganizationResponse200
     */
    data?: BaseOrganizationItem;
    /**
     * 
     * @type {GetOrganizationsResponse200AllOfRelatedObjects}
     * @memberof UpdateOrganizationResponse200
     */
    related_objects?: GetOrganizationsResponse200AllOfRelatedObjects;
}

/**
 * Check if a given object implements the UpdateOrganizationResponse200 interface.
 */
export function instanceOfUpdateOrganizationResponse200(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateOrganizationResponse200FromJSON(json: any): UpdateOrganizationResponse200 {
    return UpdateOrganizationResponse200FromJSONTyped(json, false);
}

export function UpdateOrganizationResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganizationResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : BaseOrganizationItemFromJSON(json['data']),
        'related_objects': !exists(json, 'related_objects') ? undefined : GetOrganizationsResponse200AllOfRelatedObjectsFromJSON(json['related_objects']),
    };
}

export function UpdateOrganizationResponse200ToJSON(value?: UpdateOrganizationResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'data': BaseOrganizationItemToJSON(value.data),
        'related_objects': GetOrganizationsResponse200AllOfRelatedObjectsToJSON(value.related_objects),
    };
}

