/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePersonRequestAllOf
 */
export interface UpdatePersonRequestAllOf {
    /**
     * The name of the person
     * @type {string}
     * @memberof UpdatePersonRequestAllOf
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdatePersonRequestAllOf interface.
 */
export function instanceOfUpdatePersonRequestAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdatePersonRequestAllOfFromJSON(json: any): UpdatePersonRequestAllOf {
    return UpdatePersonRequestAllOfFromJSONTyped(json, false);
}

export function UpdatePersonRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePersonRequestAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function UpdatePersonRequestAllOfToJSON(value?: UpdatePersonRequestAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

