/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserIdsAllOf
 */
export interface UserIdsAllOf {
    /**
     * The list of user IDs
     * @type {Array<number>}
     * @memberof UserIdsAllOf
     */
    data?: Array<number>;
}

/**
 * Check if a given object implements the UserIdsAllOf interface.
 */
export function instanceOfUserIdsAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserIdsAllOfFromJSON(json: any): UserIdsAllOf {
    return UserIdsAllOfFromJSONTyped(json, false);
}

export function UserIdsAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIdsAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function UserIdsAllOfToJSON(value?: UserIdsAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
    };
}

