/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The object of UserConnections
 * @export
 * @interface UserConnectionsResponse200AllOfData
 */
export interface UserConnectionsResponse200AllOfData {
    /**
     * The third party ID or false in case the ID is not found
     * @type {string}
     * @memberof UserConnectionsResponse200AllOfData
     */
    google?: string;
}

/**
 * Check if a given object implements the UserConnectionsResponse200AllOfData interface.
 */
export function instanceOfUserConnectionsResponse200AllOfData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserConnectionsResponse200AllOfDataFromJSON(json: any): UserConnectionsResponse200AllOfData {
    return UserConnectionsResponse200AllOfDataFromJSONTyped(json, false);
}

export function UserConnectionsResponse200AllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserConnectionsResponse200AllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'google': !exists(json, 'google') ? undefined : json['google'],
    };
}

export function UserConnectionsResponse200AllOfDataToJSON(value?: UserConnectionsResponse200AllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'google': value.google,
    };
}

