/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetLeadSourcesResponse200,
} from '../models';
import {
    GetLeadSourcesResponse200FromJSON,
    GetLeadSourcesResponse200ToJSON,
} from '../models';

/**
 * LeadSourcesApi - interface
 * 
 * @export
 * @interface LeadSourcesApiInterface
 */
export interface LeadSourcesApiInterface {
    /**
     * Returns all lead sources. Please note that the list of lead sources is fixed, it cannot be modified. All leads created through the Pipedrive API will have a lead source `API` assigned. 
     * @summary Get all lead sources
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadSourcesApiInterface
     */
    getLeadSourcesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetLeadSourcesResponse200>>;

    /**
     * Returns all lead sources. Please note that the list of lead sources is fixed, it cannot be modified. All leads created through the Pipedrive API will have a lead source `API` assigned. 
     * Get all lead sources
     */
    getLeadSources(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetLeadSourcesResponse200>;

}

/**
 * 
 */
export class LeadSourcesApi extends runtime.BaseAPI implements LeadSourcesApiInterface {

    /**
     * Returns all lead sources. Please note that the list of lead sources is fixed, it cannot be modified. All leads created through the Pipedrive API will have a lead source `API` assigned. 
     * Get all lead sources
     */
    async getLeadSourcesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetLeadSourcesResponse200>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["api_token"] = this.configuration.apiKey("api_token"); // api_key authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["leads:read", "leads:full"]);
        }

        const response = await this.request({
            path: `/leadSources`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetLeadSourcesResponse200FromJSON(jsonValue));
    }

    /**
     * Returns all lead sources. Please note that the list of lead sources is fixed, it cannot be modified. All leads created through the Pipedrive API will have a lead source `API` assigned. 
     * Get all lead sources
     */
    async getLeadSources(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetLeadSourcesResponse200> {
        const response = await this.getLeadSourcesRaw(initOverrides);
        return await response.value();
    }

}
